### ISSUE TITLE
Move Vote Plugin to Jlayout

### ISSUE THREAD

**Issue by javigomez** [joomla-projects/cms-naked#58]
This part of the Vote plugin could be moved to a JLayout:
https://github.com/joomla/joomla-cms/blob/15d6895995e6dc1b3644bb1bb3d72744c29f165b/plugins/content/vote/vote.php#L95-L106

**Comment by viryagroupdev** [comment]
https://github.com/joomla-projects/cms-naked/blob/master/plugins/content/vote/vote.php is it not already?

**Comment by wilsonge** [comment]
sorry that was me above :P forgot i was on company account. But point stands - hasn't it already been done @javigomez ?

**Comment by javigomez** [comment]
oops, you are right. Closing :P
